[ids]
*

[main]
leftmeta = overload(supernav, leftmeta)
rightmeta = overload(supernav, rightmeta)
mouse1 = C-right
mouse2 = C-left
mouse3 = leftmeta

[supernav:M]
left = home
right = end
enter = C-enter
